version: '3'
services:
  discoveryservice:
    build: discoveryservice
    image: proget.euleraerospace.com/docker-private/discoveryservice
    ports: 
      - "8761:8761"

  configurationservice:
    build: configurationservice
    image: proget.euleraerospace.com/docker-private/configurationservice  # goes to local registry
    ports: 
      - "9000:9000"
    depends_on:
      - "discoveryservice"  

  gatewayservice:
    build: gatewayservice
    image: proget.euleraerospace.com/docker-private/gatewayservice
    ports: 
      - "8080:8080"
    depends_on:
      - "discoveryservice"  
      - "configurationservice"

  counterservice:
    build: counterservice
    image: proget.euleraerospace.com/docker-private/counterservice
    ports: 
      - "9999:9999"
    depends_on:
      - "discoveryservice"  
      - "gatewayservice"
      - "configurationservice"
  
  