version: '3'
services:
  discoveryservice:
    image: proget.euleraerospace.com/docker-private/library/discoveryservice:latest
    ports: 
      - "8761:8761"

  configurationservice:
    image: proget.euleraerospace.com/docker-private/library/configurationservice:latest  
    ports: 
      - "9000:9000"
    depends_on:
      - "discoveryservice"  

  gatewayservice:
    image: proget.euleraerospace.com/docker-private/library/gatewayservice:latest
    ports: 
      - "8080:8080"
    depends_on:
      - "discoveryservice"  
      - "configurationservice"

  counterservice:
    image: proget.euleraerospace.com/docker-private/library/counterservice:latest
    ports: 
      - "8000:8000"
    depends_on:
      - "discoveryservice"  
      - "gatewayservice"
      - "configurationservice"
  
  