version: '3'
services:
  discoveryservice:
    build: discoveryservice
    image: proget.euleraerospace.com/docker-private/library/discoveryservice:${TAG}
    ports: 
      - "8761:8761"

  configurationservice:
    build: configurationservice
    image: proget.euleraerospace.com/docker-private/library/configurationservice:${TAG}
    ports: 
      - "9000:9000"
    depends_on:
      - "discoveryservice"  

  gatewayservice:
    build: gatewayservice
    image: proget.euleraerospace.com/docker-private/library/gatewayservice:${TAG}
    ports: 
      - "8080:8080"
    depends_on:
      - "discoveryservice"  
      - "configurationservice"

  counterservice:
    build: counterservice
    image: proget.euleraerospace.com/docker-private/library/counterservice:${TAG}
    ports: 
      - "8000:8000"
    depends_on:
      - "discoveryservice"  
      - "gatewayservice"
      - "configurationservice"
  
  